#! /bin/bash

# Ensure CLI docs match latest GetEnvoy docs
# TODO: temporarily disabled until next release
# ./ci/regen

if [ "$(git status --porcelain -uno)" != "" ]; then
    echo "The following CLI docs need to be regenerated:"
    git status --porcelain -v -uno
    git --no-pager diff
    exit 1
fi
