# `name` value will appear "as is" in the badge.
# See https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository
# yamllint --format github .github/workflows/commit.yaml
---
name: "build"

env:
  USAGE_DOC: "site/content/usage/_index.md"

on:
  # We run tests on non-tagged pushes to master
  push:
    tags: ''
    branches: master
  # We also run tests on pull requests targeted at the master branch.
  pull_request:
    branches: master
  # workflow_dispatch will let us manually trigger the workflow from GitHub actions dashboard.
  # For example, you can try to build a branch without raising a pull request.
  # See https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  check-usage:
    name: "Check usage.md"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Ensure ${{ env.USAGE_DOC }} matches tetratelabs/func-e"
        run: .github/check-usage.sh ${{ env.USAGE_DOC }}
